application: maxjaderberg
version: dev
runtime: python
api_version: 1


handlers:

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /media
  static_dir: media

- url: /
  static_files: static/home.html
  upload: static/home.html


